import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/base/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-800">


        {/* Main content */}
        <main className="min-h-screen">{children}</main>
          {/* Global footer */}
          <Footer/>
        
          {/* React Portals */}
          <div id="modal-root"></div>
      </body>
    </html>
  );
}
