import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/base/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>


        {/* Main content */}
        <main>{children}</main>
        
        {/* React Portals */}
        <div id="modal-root"></div>

        {/* Global footer */}
        <Footer/>
      </body>
    </html>
  );
}
